
# Remove Docker Packages

# - name: Remove packages
#   become: true
#   ansible.builtin.apt:
#     name: "{{ item }}"
#     state: absent
#     update_cache: true
#   loop:
#     - docker.io 
#     - docker-doc 
#     - docker-compose 
#     - podman-docker 
#     - containerd runc


# Install Install Docker Repos

- name: Setup keyrings
  become: true
  ansible.builtin.shell:
    cmd:  install -m 0755 -d /usr/share/keyrings

- name: Check that the docker.asc exists
  become: true
  stat:
    path: /usr/share/keyrings/docker.asc
  register: docker_keyring

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.get_url:
    checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker.asc
    mode: '0644'
    force: true
  when: not docker_keyring.stat.exists

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc]
      https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  when: not docker_keyring.stat.exists

- name: Update apt package index (Docker repository)
  become: yes
  apt:
    update_cache: yes
  when: not docker_keyring.stat.exists

- name: Install Docker and related packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true

- name: Ensure docker deamon is running
  ansible.builtin.sysvinit:
    name: docker
    state: started
  become: true

- name: All user to use docker without sudo
  become: true
  ansible.builtin.shell:
    cmd: "gpasswd -a {{ lookup('env', 'USER') }} docker"

- name: Adjusting permissions of docker sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '666 '
