
# Remove Docker Packages

- name: Remove packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    update_cache: true
  loop:
    - docker.io 
    - docker-doc 
    - docker-compose 
    - podman-docker 
    - containerd runc


# Install Install Docker Repos

- name: Setup keyrings
  become: true
  ansible.builtin.shell:
    cmd:  install -m 0755 -d /etc/apt/keyrings

# - name: Check that the docker.asc exists
#   become: true
#   stat:
#     path: /etc/apt/trusted.gpg.d/docker.asc
#   register: docker_keyring

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.asc
    state: present

- name: Setup keyrings
  become: true
  ansible.builtin.shell:
    cmd:  install -m 0755 -d /etc/apt/keyrings
  
- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/trusted.gpg.d/docker.asc]
      https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    filename: docker
    state: present



- name: Update apt package index (Docker repository)
  become: yes
  apt:
    update_cache: yes
 #when: not terraform_bin.stat.exists


- name: Install Docker and related packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable and start Docker services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service