remove_packages:
  # Unneeded Docker Packages
  - docker.io 
  - docker-doc 
  - docker-compose 
  - podman-docker 
  - containerd runc

install_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin
